### ISSUE TITLE
Game hangs when sleeping in Aeris house with SYW and Vulkan renderer

### ISSUE THREAD

**Issue by malvarenga123** [satsukiyatoshi/FF7_SYW_Unified#1]
When you go upstairs to sleep in her house you can see a black rectangle:

![black_rectangle](https://github.com/satsukiyatoshi/FF7_SYW_Unified/assets/61893389/f675adcf-e7b0-4226-a876-652d18b4945e)

When you finish talking with her, the game will hang at: "...seem

![vulkan](https://github.com/satsukiyatoshi/FF7_SYW_Unified/assets/61893389/5939f57b-a236-46eb-b91c-5d2de51bd063)

If I change to DX11, the black rectangle is also there, but the game won't hang:

![dx11](https://github.com/satsukiyatoshi/FF7_SYW_Unified/assets/61893389/8a43fcc7-6064-4371-88d0-7142e5c09619)

At first I thought this was an issue with Vulkan and FFNx, but I tried with the vanilla 1.02 version of the game and the game does not hang there:

![vulkan_vanilla](https://github.com/satsukiyatoshi/FF7_SYW_Unified/assets/61893389/288bfef0-6c6d-4cb6-abd7-228bf28b6b68)

You can see the log file here with renderer_debug = true: https://pastebin.com/Ujf2X6Pk
I'm also attaching a save file outside her house and an Ochu savestate.

[Save.zip](https://github.com/satsukiyatoshi/FF7_SYW_Unified/files/14437028/Save.zip)

**Comment by malvarenga123** [comment]
Pinging @julianxhokaxhiu to see if he has any idea of what could be happening

**Comment by satsukiyatoshi** [comment]
witch options do you use in the launcher (each option of each tab).
if it's crashing only witch some render i don't get why another exe will not crash.
for the black rectangle i can't reproduice the bug.
![image](https://github.com/satsukiyatoshi/FF7_SYW_Unified/assets/8547498/634cf688-7fdc-47db-8234-a73d5c4afa35)

edit : i was able to reproduice the bug with english's version of the game, gona test other langs

**Comment by satsukiyatoshi** [comment]
ok the black rectange will be fixed in next update, it's related to a fix by L@azaro to correct the doors on this field, i need to report the fix on all flevels to be able to use my background stuff without bug.

i can't reproduise the game freeze, nevemind the lang or the render

**Comment by malvarenga123** [comment]
Here is my settings.ini:

```
FFNxAnalogControllerArun
FFNxNoCd
FFNxShowStats
FFNXMusicResume
FFNxAnisotropic
FFNxAnalogController
axl3dbattle
FFNxGamutNtsc
FFNxLighting
graphicsMagics
graphicsBattles
graphicsWorldMap
graphicsAnimations
graphicsMiniGames
graphicsFields
;;;;gameplayComboPatchs::::Unlimited Items####
;;;;HelpList::::####
;;;;FFNxComboPatchs::::Transparent dialog windows (75%)####
;;;;FFNxFps::::30 fps figths####
;;;;FFNxSpeedhackMax::::4.0####
;;;;FFNxSpeedhackMin::::1.0####
;;;;FFNxSpeedhackStep::::1.0####
;;;;FFNxContolerDeathzoneRT::::0.1####
;;;;FFNxContolerDeathzoneLT::::0.1####
;;;;FFNxContolerDeathzoneStick::::0.1####
;;;;FFNxAudioSample::::48000####
;;;;FFNxIR::::x2####
;;;;FFNxAudioChannels::::2.0####
;;;;FFNxAA::::x4####
;;;;FFNxResolution::::Automatic####
;;;;FFNxHDR::::Automatic####
;;;;FFNxRatio::::4/3 (Original game)####
;;;;FFNxScreen::::Windowed####
;;;;FFNx3dEngine::::Vulkan####
;;;;gameplayMods::::Original gameplay####
;;;;soundsVoices::::None####
;;;;soundsFMV::::Original audio tracks####
;;;;soundsAmbients::::None####
;;;;soundsSfx::::Original sound effects####
;;;;soundsMusics::::FFNx FF7Music####
;;;;graphicsAddTextures::::None####
;;;;graphicsModels3Dm::::NinoStyle Chibi####
;;;;graphicsModels3Dw::::NinoStyle Chibi####
;;;;graphicsMenu::::Aavock UI 1:1 Remastered####
;;;;graphicsFMV::::HD videos 30 fps####
;;;;graphicsModels3Dc::::NinoStyle Realist####
;;;;graphicsModels3Df::::NinoStyle Chibi####
;;;;presets::::None####
;;;;langGame::::English####
Patchslist;;;;Transparent combat windows (75%)####
Patchslist;;;;Transparent dialog windows (75%)####
GameplayPatchslist;;;;save anywhere####
GameplayPatchslist;;;;True Honey Bee Inn####
```

**Comment by malvarenga123** [comment]
Hi Satsuki, an update to this issue. It's related to the HD fonts.
I'm using your mods with 7th Heaven now and I got the lockup on Aeris' House and on Sector 6 with the "In may veins courses the blood of the Ancients." part. So I disabled only the HD fonts in the Unified UI configuration and there was no lockup.

**Comment by satsukiyatoshi** [comment]
could you try auto rendering instead of forcing vulkan ?

**Comment by malvarenga123** [comment]
> could you try auto rendering instead of forcing vulkan ?

Vulkan is the only one that works with my video card (AMD R9 280X). OpenGL does not display any models and the screen keeps blinking with DX11.

**Comment by satsukiyatoshi** [comment]
AS i can't reproduce thsi bug and as vulkan is much more instable than other renderer, it's probably related to a combination of your gpu + your dirvers + vulkan.
Have you tried D3D12 (dx12) ? it's working fine with most amd gpu (better thant vulkan)

**Comment by malvarenga123** [comment]
> AS i can't reproduce thsi bug and as vulkan is much more instable than other renderer, it's probably related to a combination of your gpu + your dirvers + vulkan. Have you tried D3D12 (dx12) ? it's working fine with most amd gpu (better thant vulkan)

You mean **HD fonts** + my gpu + my drivers + vulkan, because regular fonts + my gpu + my drivers + vulkan works fine.
It's something very specific to those HD fonts on a black screen (those times that only Cloud can hear a voice).

DX12 falls back to DX11 on Windows 7.
To be fair, I do think there's something very strange going on with FFNx's implementation/use of BGFX renderer. The first question in their FAQ is related artifacts on AMD GPU's, but if you look [here](https://github.com/bkaradzic/bgfx/issues) there's no open issue specific to AMD GPU's or drivers. Also I ONLY get artifacts with FFNx, no other game using Vulkan, DX11 or OpenGL has a single problem on my machine, so my guess is that the FFNx devs are doing something that Nvidia cards just ignore but is not really compliant with BGFX.

**Comment by satsukiyatoshi** [comment]
So you use win7 + vulkan it's logic you got bugs, vulkan in bgfx is immature, and win7 isn't officialy supported anymore by FFNx it's a way too old OS.
AMD drivers deos not help (it's even listed as showing artifact with dx11 depending drivers version, so AMD + DX11 + most AMD drivers = visual glitch.

long story short, it related to your system / bgfx, you can try to report to FFNx's discord  but with such old system, not sure there's a solution

**Comment by malvarenga123** [comment]
> AMD drivers deos not help (it's even listed as showing artifact with dx11 depending drivers version, so AMD + DX11 + most AMD drivers = visual glitch.

As I said, there's nothing in BGFX's github indicating issues related to AMD cards or drivers. All problems with AMD cards seem exclusive to FFNx.

The log I posted (https://pastebin.com/Ujf2X6Pk) has some errors that should help with debugging, but FFNx devs do not support issues related to mods (this issue is related to the HD fonts mod), so there's nothing to be done.
